Issue page
INF2A-Team-2/VisconSupportApp pull request #14
Opened 2023-10-29 17:33 UTC by penguin-vd

2023-10-29 17:47 UTC, luuk180 approved these changes

2023-10-29 17:47 UTC, luuk180 commented
Guus, zou jij hier nog naar willen kijken?

2023-10-30 11:47 UTC, ZoutigeWolf requested changes
shit doesn't even compile
<img width="1314" alt="image" src="https://github.com/INF2A-Team-2/VisconSupportApp/assets/80846801/f15e9fe4-fad3-4694-92b5-95df6b1d3d44">

2023-10-30 12:00 UTC, ZoutigeWolf commented on src/api/machine.ts
> +        axios.get(URL, RequestConfig())
URL variable is onnodig, je kan gwn de url gwn direct in axios gooien.

2023-10-30 19:08 UTC, ZoutigeWolf commented
K kijk vanavond ben aan t werk

2023-10-31 13:03 UTC, ZoutigeWolf approved these changes
goed.

2023-10-31 13:03 UTC, merged