solved issues page -> expanding issues
INF2A-Team-2/VisconSupportApp pull request #20
Opened 2023-11-15 12:20 UTC by patchzyy

2023-11-15 15:31 UTC, ZoutigeWolf reviewed
Wrm delete je de SERVER_URL const

Ik kijk thuis verder

2023-11-16 11:22 UTC, luuk180 requested changes, later dismissed
Kan je de changes aan auth.ts er uit halen en de merge conflict fixen?

2023-11-16 11:32 UTC, ZoutigeWolf commented
is die expanding button niet gwn kk useless, in de praktijk kunnen mensen regels en regels aan tekst schrijven in die issue en dat gaat er dan vrij raar uit zien

en de css ziet er nog steeds shit uit

2023-11-16 11:35 UTC, luuk180 commented
haha jij laat er geen gras over groeien he Guus

2023-11-16 11:44 UTC, ZoutigeWolf commented
<img width="1378" alt="image" src="https://github.com/INF2A-Team-2/VisconSupportApp/assets/80846801/eac495d4-f7e6-45e5-a2f5-d9838b3222d1">

<img width="1374" alt="image" src="https://github.com/INF2A-Team-2/VisconSupportApp/assets/80846801/99551cb5-8bb6-4085-b464-5d7e6c7106f5">

het ziet er wel beter uit maar als de tekst te lang is zie je de button niet eens
en waarom is de font weight van de button anders dan de rest
en iets meer gap tussen de tekst stukken maakt t ook wat duidelijker

2023-11-16 13:58 UTC, ZoutigeWolf approved these changes
ok

2023-11-16 13:58 UTC, merged