User edit page
INF2A-Team-2/VisconSupportApp pull request #39
Opened 2023-12-06 14:53 UTC by patchzyy

2023-12-06 15:56 UTC, ZoutigeWolf requested changes
ALs ik nu iemand anders z'n id invoer kan ik die editen 

Je hebt geen userid variable nodig je maakt gwn een endpoint /account en dan krijg je je eigen shit

En gebruik a ipv Link gwn \<a href="/account">

2023-12-09 18:38 UTC, ZoutigeWolf requested changes
Ziet er opzich prima uit alleen hoef je bij de navigation header geen user null check te doen want je kan de header alleen zien als je ingelogd bent

En verwijder code die je niet meer nodig hebt zoals die use effect en die requested user id

2023-12-09 18:51 UTC, patchzyy commented
> Ziet er opzich prima uit alleen hoef je bij de navigation header geen user null check te doen want je kan de header alleen zien als je ingelogd bent
> 
> En verwijder code die je niet meer nodig hebt zoals die use effect en die requested user id

heb de cleanup gedaan alleen over welke nullcheck heb je t? ik heb volgensmij geen extra null check gemaakt, en de nullcheck bij navigationheader line 36 heb je nodig anders laad de pagina niet

2023-12-10 12:17 UTC, ZoutigeWolf requested changes
Die {} om de account knop heen zijn totaal onnodig, en waarom heb je nog steeds die useeffect op line 21 van de user editor, die endpoint bestaat niet eens

2023-12-10 12:38 UTC, ZoutigeWolf reviewed
Ziet er prima uit ik zal
vanavond ff runnen

2023-12-10 12:41 UTC, patchzyy commented
> Ziet er prima uit ik zal vanavond ff runnen

oke, als hij er eenmaal in zit en gemerged is met de UI rework, ga ik de ui hiervan helemaal overhaulen want ja heb daar geen tijd in gestoken, en dan kan ik de change password toevoegen die luuk had gemaakt, die zit hier namelijk nog niet in want die zit in andere branch

2023-12-12 08:39 UTC, ZoutigeWolf requested changes
verander de loading... naar iets van None off want nu als iemand geen phone number heeft blijft er loading staan ipv geen telefoon number

2023-12-12 11:22 UTC, closed without merging